# =========================
# ET (Boston + NYC)
# =========================
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lectures-notifier-et-10m
spec:
  timeZone: "America/New_York"
  schedule: "*/5 10-18 * * *"   # every 5 minutes from 10:00 to 18:59 ET
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: notifier
              image: ghcr.io/gordonpn/lectures-notifier:main
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: lectures-notifier-secrets
