apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-hub
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lectures.gordon-pn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-hub
                port:
                  number: 80
  tls:
    - hosts:
        - lectures.gordon-pn.com
      secretName: notification-hub-tls
